[package]
name = "steg"
version = "0.1.0"
authors = ["Dan Bottcher <dbottch1@binghamton.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#ascii = "1.0.0"
#hex = "0.4.0"
